FROM node:20.19.0 AS api-builder

WORKDIR /server

COPY api/package*.json api/yarn.lock ./
RUN corepack enable && yarn install --frozen-lockfile

COPY api/ ./
RUN yarn build

FROM node:20.19.0 AS final

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=api-builder /server/dist ./dist
COPY --from=api-builder /server/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "dist/index.js"]
